# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Color Cntrl
email: amj.krabbe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Color CNTRL technology arranges color particles through 3 transparent layers: 
  Yellow, Magenta and Cyan. 16 shades x 3 renders 4096 different colors.
baseurl: "/colorcntrl/" # the subpath of your site, e.g. /blog
url: "http://www.colorcntrl.com" # the base hostname & protocol for your site, e.g. http://example.com

#google_url: http://www.google.com
#twitter_url: http://www.twitter.com
#facebook_url: http://www.facebook.com
#instagram_url: http://www.instragram.com
linkedin_url: http://www.linkedin.com

# Build settings
markdown: kramdown
theme: minima

source: src/jekyll/
destination: docs/
port: 3031
sass: false
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock